# MIT License

# Copyright (c) 2024 DataStax, Inc.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# **THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.**

#FROM devinbostds/langflow_arm64:1.0.18
#FROM langflowai/langflow:v1.1.0
#FROM langflowai/langflow:v1.0.19.post2
# FROM langflowai/langflow-ep:v1.1.1.dev8
#FROM jordanrfrazier/lfopenshift
#FROM langflowai/langflow-ep:v1.1.1.dev11 
#FROM jordanrfrazier/pgfix:v1.0
FROM langflowai/langflow-ep:v1.1.1.dev19
WORKDIR /app

#RUN pip install -U cassio mysql-connector-python sentence-transformers langchain-huggingface langchain-astradb
RUN python3 -m venv /app/.venv && \
    /bin/bash -c "source /app/.venv/bin/activate && pip install -U langchain-huggingface mysql-connector-python langchain pydantic"

EXPOSE 7860

CMD ["langflow", "run", "--env-file", "/app/.env", "--host", "0.0.0.0", "--port", "7860"]